export type Product = {
  id: string;
  name: string;
  company: string;
  country: "中国" | "海外";
  modality: string;
  category: string;
  status: string;
  summary: string;
  specs: string[];
  sourceUrl: string;
  image?: string;
  imageCredit?: string;
  imageSource?: string;
  logo?: string;
  logoCredit?: string;
  logoSource?: string;
};

export type Paper = {
  id: string;
  title: string;
  titleEn: string;
  year: string;
  venue: string;
  type: string;
  signal: string;
  summary: string;
  innovation: string;
  limitation: string;
  url: string;
};

export const products: Product[] = [
  {
    id: "neuracle-neo",
    name: "NEO 手部运动功能代偿系统",
    company: "博睿康 · 清华大学洪波团队",
    country: "中国",
    modality: "硬膜外植入",
    category: "临床康复",
    status: "国家药监局批准上市",
    summary: "面向颈段脊髓损伤患者，以硬膜外电极采集运动意图，无线驱动气动手套完成抓握。",
    specs: ["硬膜外电极，不直接接触脑组织", "近场无线供电与信号传输", "脑电解码软件 + 气动手套闭环"],
    sourceUrl: "https://www.nmpa.gov.cn/zhuanti/cxylqx/cxylqxlm/20260313134742156.html",
    image: "https://img.cls.cn/images/20241113/9TWoR41178.png",
    imageCredit: "财联社：NEO 系统临床试验报道",
    imageSource: "https://www.cls.cn/detail/1857170",
  },
  {
    id: "neuracle-neusen-w",
    name: "NeuSen W 无线数字脑电系统",
    company: "博睿康",
    country: "中国",
    modality: "非侵入 EEG",
    category: "科研采集",
    status: "科研产品",
    summary: "面向移动、多被试和自然场景实验的无线脑电采集平台，可用于 SSVEP、运动想象与脑控设备研究。",
    specs: ["无线穿戴式采集", "支持多模态生理信号", "面向科研与 BCI 竞赛生态"],
    sourceUrl: "https://www.neuracle.cn/newsinfo/8691378.html",
    logo: "https://img.medsci.cn/a53f3a60059f28c9c1c2d31cafbf8da9c7c14ce2b576879e27c60170a9c75d05.png",
    logoCredit: "博睿康品牌标识（生物在线公司页）",
    logoSource: "https://www.bioon.com.cn/company/index/c33e28982350",
  },
  {
    id: "brainco-hand",
    name: "智能仿生手",
    company: "强脑科技 BrainCo",
    country: "中国",
    modality: "表面肌电 / 神经交互",
    category: "智能假肢",
    status: "规模化应用",
    summary: "通过残肢表面肌电识别运动意图并控制多自由度仿生手。它属于广义神经接口，不是直接采集脑信号。",
    specs: ["非侵入式肌电意图识别", "多自由度抓握控制", "强调低成本康复辅具落地"],
    sourceUrl: "https://www.brainco.cn/",
    image: "https://www.news.cn/info/20250228/40b6e918333c42f3a961af3090fecf8c/2025022840b6e918333c42f3a961af3090fecf8c_94dc11c2a78e4131bb17095487bc6159.JPG",
    imageCredit: "新华网：强脑科技智能仿生手",
    imageSource: "https://www.news.cn/info/20250228/40b6e918333c42f3a961af3090fecf8c/c.html",
  },
  {
    id: "neuroxess-system",
    name: "“三全”柔性脑机接口系统",
    company: "脑虎科技 NeuroXess",
    country: "中国",
    modality: "硬膜下柔性 ECoG",
    category: "临床沟通与运动",
    status: "GCP 注册临床试验",
    summary: "全植入、全无线、全功能的柔性皮层表面接口，聚焦高位截瘫与渐冻症患者的运动、沟通重建。",
    specs: ["柔性电极贴附皮层表面", "全链路低延迟无线系统", "结合 FES 完成功能重建"],
    sourceUrl: "https://www.neuroxess.com/news/",
    image: "https://en.neuroxess.com/assets/researchProducts2.abdabc4c.png",
    imageCredit: "脑虎科技官方科研产品素材",
    imageSource: "https://en.neuroxess.com/",
    logo: "https://www.neuroxess.com/favicon.ico",
    logoCredit: "脑虎科技官方站点标识",
    logoSource: "https://www.neuroxess.com/",
  },
  {
    id: "beinao-one",
    name: "北脑一号",
    company: "北京脑科学与类脑研究所 · 芯智达",
    country: "中国",
    modality: "硬膜外植入",
    category: "运动与语言解码",
    status: "人体临床验证",
    summary: "128 通道微型无线低功耗全植入系统，面向精细运动解码与中文语言解码。",
    specs: ["128 通道", "无线、低功耗、全植入", "硬膜外半侵入路线"],
    sourceUrl: "https://cibr.ac.cn/detail/researchAchievementpaper/502920626c2840769036d322c8aefab4",
    image: "https://www.news.cn/tech/20260326/1f9fc6705ab349eb85670e32b1907bc7/202603261f9fc6705ab349eb85670e32b1907bc7_20260326d2e201c7b0f840868f7d30811f77158a.png",
    imageCredit: "新华网：北脑一号展品",
    imageSource: "https://www.news.cn/tech/20260326/1f9fc6705ab349eb85670e32b1907bc7/c.html",
  },
  {
    id: "beinao-two",
    name: "北脑二号",
    company: "北京脑科学与类脑研究所 · 芯智达",
    country: "中国",
    modality: "皮层内柔性电极",
    category: "高通量研究",
    status: "临床前 / 工程化",
    summary: "面向高通量侵入式记录，已展示非人灵长类二维运动目标脑控，正推进无线工程机。",
    specs: ["1,024 通道有线原型", "柔性入脑电极", "目标为长期稳定高分辨记录"],
    sourceUrl: "https://cibr.ac.cn/detail/researchAchievementpaper/502920626c2840769036d322c8aefab4",
    logo: "https://cdn.carguide.com.cn/wx1cca63789857f05d/2024-04-22/1713752667596772.png",
    logoCredit: "北京脑科学与类脑研究所标识",
    logoSource: "https://cibr.ac.cn/",
  },
  {
    id: "neuralink-n1",
    name: "N1 Implant",
    company: "Neuralink",
    country: "海外",
    modality: "皮层内柔性线程",
    category: "数字设备控制",
    status: "人体可行性试验",
    summary: "以手术机器人植入柔性电极线程，记录皮层单元活动并无线输出，用于光标和辅助设备控制。",
    specs: ["1,024 电极", "全植入无线", "R1 手术机器人植入"],
    sourceUrl: "https://neuralink.com/trials/device-control/",
    logo: "/brands/neuralink.svg",
    logoCredit: "Neuralink 标识（公开领域）",
    logoSource: "https://commons.wikimedia.org/wiki/File:Neuralink_logo.svg",
  },
  {
    id: "synchron-stentrode",
    name: "Stentrode",
    company: "Synchron",
    country: "海外",
    modality: "血管内植入",
    category: "辅助沟通",
    status: "临床试验",
    summary: "经颈静脉将支架式电极部署于脑血管内，避免开颅，实现数字设备控制。",
    specs: ["血管内电极阵列", "全植入无线", "低手术负担"],
    sourceUrl: "https://synchron.com/technology",
    image: "https://www.bioworld.com/ext/resources/BMT-source/2022/Synchron-Stentrode-brain-implant.webp?t=1671575274",
    imageCredit: "BioWorld：Synchron Stentrode 产品图",
    imageSource: "https://www.bioworld.com/articles/692600-australias-synchron-raises-au110m-to-advance-endovascular-brain-computer-interface",
  },
  {
    id: "openbci-galea",
    name: "Galea",
    company: "OpenBCI",
    country: "海外",
    modality: "非侵入多模态",
    category: "XR 神经交互",
    status: "科研产品",
    summary: "面向 XR 的开放式多模态生理采集头显，整合 EEG、EMG、EOG、EDA 与眼动扩展。",
    specs: ["多模态生理信号", "开放开发生态", "面向 VR/AR 研究"],
    sourceUrl: "https://shop.openbci.com/products/galea",
    image: "https://shop.openbci.com/cdn/shop/files/2025-galea-neon-transparent-glow-WEB_1500x.png?v=1759332990",
    imageCredit: "OpenBCI 官方商店",
    imageSource: "https://shop.openbci.com/products/galea",
  },
  {
    id: "precision-layer7",
    name: "Layer 7 Cortical Interface",
    company: "Precision Neuroscience",
    country: "海外",
    modality: "高密度微型 ECoG",
    category: "皮层记录与数字设备控制",
    status: "FDA 510(k) 获批；临床研究",
    summary: "超薄、高密度皮层表面阵列，通过微切口置入并贴合脑表面，探索兼顾高带宽、可移除性与较低组织损伤的接口路线。",
    specs: ["1,024 电极阵列", "不穿透脑组织", "可移除、可升级的表面接口"],
    sourceUrl: "https://www.precisionneuro.io/our-technology",
    image: "https://cdn.sanity.io/images/qt1uzzfj/staging/7b67303494f698b1f4138e05dc0d3df3b0d6bd27-5273x3515.png?auto=format&fit=crop&h=1599&q=95&rect=0%2C2%2C5273%2C3513&w=2400",
    imageCredit: "Precision Neuroscience 官方产品素材",
    imageSource: "https://www.precisionneuro.io/our-technology",
  },
  {
    id: "paradromics-connexus",
    name: "Connexus BCI",
    company: "Paradromics",
    country: "海外",
    modality: "皮层内微电极",
    category: "语音与计算机控制",
    status: "Connect-One 人体临床研究",
    summary: "面向严重运动障碍患者的全植入高带宽接口，以单神经元级记录配合解码模型恢复合成语音、文本和计算机控制。",
    specs: ["421 枚皮层内微电极", "全植入、全无线", "目标长期稳定记录超过 10 年"],
    sourceUrl: "https://paradromics.com/connexus/",
    image: "https://cdn.prod.website-files.com/65cd1a545634de6df4638d42/67d03815c109c8cd115b16cf__82A6249_samller.png",
    imageCredit: "Paradromics 官方 Connexus 素材",
    imageSource: "https://paradromics.com/connexus/",
  },
  {
    id: "blackrock-moveagain",
    name: "MoveAgain BCI",
    company: "Blackrock Neurotech",
    country: "海外",
    modality: "皮层内 Utah Array",
    category: "辅助沟通与运动控制",
    status: "FDA 突破性医疗器械认定；研发中",
    summary: "建立在长期人体 Utah Array 研究基础上的植入式系统，解码运动意图并控制光标、轮椅或辅助设备。",
    specs: ["皮层内 Utah Array", "无线传输至外部设备", "长期人体研究积累"],
    sourceUrl: "https://blackrockneurotech.com/our-tech/",
    image: "https://blackrockneurotech.com/wp-content/themes/edesign/webroot/images/header-img.png?v=.2",
    imageCredit: "Blackrock Neurotech 官方产品素材",
    imageSource: "https://blackrockneurotech.com/insights/blackrock-neurotechs-moveagain-brain-computer-interface-system-receives-breakthrough-device-designation-from-the-fda/",
  },
  {
    id: "kernel-flow2",
    name: "Kernel Flow 2",
    company: "Kernel",
    country: "海外",
    modality: "非侵入 TD-DOT / EEG",
    category: "脑功能测量与 AI 研究",
    status: "科研与临床服务产品",
    summary: "便携式高密度光学脑成像与电信号采集平台，重点服务神经科学、认知、心理健康和脑数据 AI 研究；它不是直接控制型 BCI。",
    specs: ["3,500 个 TD-DOT 测量通道", "全头覆盖与运动鲁棒性", "适合大规模脑数据与 AI 研究"],
    sourceUrl: "https://www.kernel.com/developers",
    logo: "https://neuronewsinternational.com/wp-content/uploads/sites/3/2023/08/Kernel-logo-featured.jpg",
    logoCredit: "Kernel 品牌标识（NeuroNews）",
    logoSource: "https://www.kernel.com/",
  },
];

export const papers: Paper[] = [
  {
    id: "brain-to-voice-2025",
    title: "流式脑到语音神经假体",
    titleEn: "A streaming brain-to-voice neuroprosthesis",
    year: "2025", venue: "Nature Neuroscience", type: "语音 BCI", signal: "ECoG",
    summary: "将神经活动持续映射为接近实时的语音，并恢复语调、节奏和个体声音特征。",
    innovation: "从离线或分段解码推进到流式合成，显著缩短交流延迟。",
    limitation: "单一受试者、个体化训练，跨人泛化仍未解决。",
    url: "https://pubmed.ncbi.nlm.nih.gov/40164740/",
  },
  {
    id: "speech-neuroprosthesis-2023",
    title: "高性能语音神经假体",
    titleEn: "A high-performance speech neuroprosthesis",
    year: "2023", venue: "Nature", type: "语音 BCI", signal: "皮层内 spikes",
    summary: "在大词表自由句子上实现 62 词/分钟，证明高分辨皮层内信号可接近自然交流速度。",
    innovation: "高速神经解码与语言模型联合，突破大词表实时通信瓶颈。",
    limitation: "需要大量个体数据和每日适配，植入长期稳定性仍是临床门槛。",
    url: "https://www.nature.com/articles/s41586-023-06377-x",
  },
  {
    id: "seeg-transfer-2025",
    title: "分布式脑记录上的跨被试迁移",
    titleEn: "Transfer learning via distributed brain recordings",
    year: "2025", venue: "Nature Communications", type: "泛化解码", signal: "sEEG",
    summary: "从大队列分布式 sEEG 中学习共享潜在流形，为不同电极覆盖的患者初始化语音解码器。",
    innovation: "把跨被试泛化从口号落实为共享表征与个体适配框架。",
    limitation: "仍依赖共同任务范式，真实失语患者上的验证有限。",
    url: "https://www.nature.com/articles/s41467-025-63825-0",
  },
  {
    id: "labram-2024",
    title: "LaBraM：大规模 EEG 通用表征",
    titleEn: "Large Brain Model for Learning Generic Representations",
    year: "2024", venue: "ICLR Spotlight", type: "神经基础模型", signal: "EEG",
    summary: "通过离散神经 tokenizer 与掩码神经谱预测，在异构 EEG 数据上学习通用表示。",
    innovation: "把跨数据集预训练引入 EEG，并用神经码本统一连续信号。",
    limitation: "对通道配置、临床迁移和低资源任务的真实增益仍需严格审计。",
    url: "https://arxiv.org/abs/2405.18765",
  },
  {
    id: "eegpt-2024",
    title: "EEGPT：通用可靠的 EEG 预训练 Transformer",
    titleEn: "EEGPT: Pretrained Transformer for Universal EEG",
    year: "2024", venue: "NeurIPS", type: "神经基础模型", signal: "EEG",
    summary: "以 10M 参数 Transformer 学习可迁移 EEG 特征，强调跨任务、跨设备与抗噪能力。",
    innovation: "用双重自监督目标结合空间与时序表征。",
    limitation: "统一基准下与小型监督模型的收益仍需持续比较。",
    url: "https://proceedings.neurips.cc/paper_files/paper/2024/hash/4540d267eeec4e5dbd9dae9448f0b739-Abstract-Conference.html",
  },
  {
    id: "layer7-2026",
    title: "Layer 7 的实时术中神经解码",
    titleEn: "Initial experience with the Layer 7 micro-ECoG interface",
    year: "2026", venue: "同行评审论文", type: "高密度硬件", signal: "µECoG",
    summary: "在人类运动皮层上验证 1,024 通道微电极阵列的术中记录和实时解码能力。",
    innovation: "高密度表面记录兼顾空间分辨率、覆盖与组织安全。",
    limitation: "短时术中记录不能替代长期全植入稳定性证据。",
    url: "https://pubmed.ncbi.nlm.nih.gov/41621103/",
  },
  {
    id: "stentrode-2023",
    title: "全植入血管内 BCI 的四例安全性研究",
    titleEn: "Assessment of Safety of a Fully Implanted Endovascular BCI",
    year: "2023", venue: "JAMA Neurology", type: "临床转化", signal: "血管内 ECoG",
    summary: "报告四名重度瘫痪患者的全植入血管内 BCI 安全性与家庭数字设备使用。",
    innovation: "以血管通路降低植入门槛，形成不同于开颅电极的临床路线。",
    limitation: "样本很小，信号带宽与高自由度控制能力有限。",
    url: "https://pubmed.ncbi.nlm.nih.gov/36622685/",
  },
  {
    id: "bigp3bci-2025",
    title: "bigP3BCI：标准化的大规模 P300 数据集",
    titleEn: "An Open, Diverse and Machine Learning Ready P300 BCI Dataset",
    year: "2025", venue: "PhysioNet", type: "数据与基准", signal: "EEG",
    summary: "整合多项 P300 拼写研究并按新兴 IEEE P2731 术语标准组织，便于复用与跨会话建模。",
    innovation: "把历史异构数据转化为机器学习可用的标准化公共资源。",
    limitation: "以 P300 范式为主，不能代表通用 EEG 解码的全部分布。",
    url: "https://physionet.org/content/bigp3bci/",
  },
  {
    id: "memristor-adaptive-bci-2025",
    title: "忆阻器自适应神经形态 BCI 解码器",
    titleEn: "A memristor-based adaptive neuromorphic decoder for brain–computer interfaces",
    year: "2025", venue: "Nature Electronics", type: "忆阻器计算", signal: "EEG / SSVEP / ErrP",
    summary: "以 128k 单元忆阻器芯片完成低功耗在线解码，并在十名参与者的四自由度无人机控制中验证脑—解码器协同适应。",
    innovation: "把存内计算、错误相关电位反馈和在线更新合并为可运行的闭环硬件系统。",
    limitation: "任务仍以结构化非侵入式范式为主，器件漂移、批次差异和长期耐久性仍需扩大验证。",
    url: "https://www.nature.com/articles/s41928-025-01340-2",
  },
  {
    id: "memristor-neural-analysis-2020",
    title: "忆阻器阵列的高能效神经信号分析",
    titleEn: "Neural signal analysis with memristor arrays towards high-efficiency brain–machine interfaces",
    year: "2020", venue: "Nature Communications", type: "忆阻器计算", signal: "神经电信号",
    summary: "用忆阻器阵列在模拟域实现滤波与癫痫神经信号识别，展示约 400 倍功效提升的概念验证。",
    innovation: "把神经信号预处理和解码同时映射到存内模拟计算，而非在冯·诺依曼架构中搬运数据。",
    limitation: "属于实验室级概念验证，距离可植入、可校准、长期稳定的完整系统仍有距离。",
    url: "https://www.nature.com/articles/s41467-020-18105-4",
  },
  {
    id: "minimally-invasive-thinfilm-2025",
    title: "可微创递送的 1,024 通道薄膜皮层阵列",
    titleEn: "Minimally invasive implantation of scalable high-density cortical microelectrode arrays for multimodal neural decoding and stimulation",
    year: "2025", venue: "Nature Biomedical Engineering", type: "柔性电极", signal: "µECoG",
    summary: "通过无需开颅的微创递送方式部署 1,024 通道薄膜阵列，并展示记录、刺激及多模态神经解码。",
    innovation: "把高密度皮层覆盖与可逆、低组织损伤的递送路径放到同一工程框架中。",
    limitation: "长期证据主要来自动物模型，人类部分仍是短时术中可行性研究。",
    url: "https://www.nature.com/articles/s41551-025-01501-w",
  },
  {
    id: "bisc-65536-2025",
    title: "65,536 电极、1,024 通道无线硬膜下 BCI",
    titleEn: "A wireless subdural-contained brain–computer interface with 65,536 electrodes and 1,024 channels",
    year: "2025", venue: "Nature Electronics", type: "柔性电极", signal: "µECoG",
    summary: "在 50 微米柔性 CMOS 基底上集成 65,536 个电极、无线供电和双向通信，可同时选择记录 1,024 通道。",
    innovation: "把电极、信号处理、遥测和供电整合在硬膜下单一基底，显著提高可扩展性。",
    limitation: "长期记录目前到猪两周、非人灵长类两个月，尚无慢性人体植入证据。",
    url: "https://www.nature.com/articles/s41928-025-01509-9",
  },
  {
    id: "tent-electrode-2024",
    title: "可降解、自展开的脑皮层帐篷电极",
    titleEn: "A biodegradable and self-deployable electronic tent electrode for brain cortex interfacing",
    year: "2024", venue: "Nature Electronics", type: "柔性电极", signal: "皮层电信号",
    summary: "利用可形变结构让电极经较小手术入口进入后自行展开，覆盖更大皮层表面并在任务结束后降解。",
    innovation: "将微创递送、展开几何和生物可降解材料组合，减少大范围开颅与二次取出需求。",
    limitation: "材料降解时间、展开一致性与长期高密度信号质量仍需临床级验证。",
    url: "https://www.nature.com/articles/s41928-024-01216-x",
  },
  {
    id: "kirigami-electrode-2026",
    title: "面向灵长类脑表面的柔性剪纸微电极阵列",
    titleEn: "Flexible kirigami microelectrode arrays for neuronal activity recordings in non-human primate brains",
    year: "2026", venue: "Nature Electronics", type: "柔性电极", signal: "ECoG",
    summary: "以剪纸结构提升阵列对弯曲脑表面的顺应性，在非人灵长类上记录神经活动。",
    innovation: "用几何结构而非单纯降低材料模量来释放应变，兼顾贴合范围和电极完整性。",
    limitation: "仍是动物研究；手术操作、长期封装和人体尺度制造尚待验证。",
    url: "https://www.nature.com/articles/s41928-025-01560-6",
  },
  {
    id: "neuript-2025",
    title: "NeurIPT：面向多种神经接口的 EEG 基础模型",
    titleEn: "NeurIPT: Foundation Model for Neural Interfaces",
    year: "2025", venue: "NeurIPS", type: "神经基础模型", signal: "EEG",
    summary: "结合三维电极坐标、幅值感知掩码预训练与渐进式混合专家，在八项 EEG 基准上学习跨设置表征。",
    innovation: "把真实电极空间位置直接纳入编码，针对不同导联布局与时间模式设计预训练机制。",
    limitation: "主要证据仍来自公开基准；临床前瞻数据、冻结迁移和公平计算预算比较更关键。",
    url: "https://papers.nips.cc/paper_files/paper/2025/file/dd9c5ce8803e1898d438e636fbae0236-Paper-Conference.pdf",
  },
  {
    id: "eeg-fm-worth-it-2026",
    title: "EEG 基础模型真的值得吗？",
    titleEn: "Are EEG Foundation Models Worth It? Comparative Evaluation with Traditional Decoders in Diverse BCI Tasks",
    year: "2026", venue: "ICLR", type: "基准与评估", signal: "EEG",
    summary: "在多类 BCI 任务、数据规模与迁移设置下，对 EEG 基础模型和传统解码器进行统一比较。",
    innovation: "把关注点从单模型榜单转向数据量、迁移协议、统计显著性与计算成本的公平评估。",
    limitation: "结论依赖所选数据集、下游任务和微调预算，不能直接外推到所有临床 EEG 场景。",
    url: "https://openreview.net/forum?id=5Xwm8e6vbh",
  },
  {
    id: "sleepgpt-2026",
    title: "SleepGPT：统一时频睡眠基础模型",
    titleEn: "A unified time-frequency foundation model for sleep decoding",
    year: "2026", venue: "Nature Communications", type: "EEG 解码", signal: "PSG / EEG",
    summary: "在 8,377 名受试者、86,335 小时 PSG 上预训练，统一处理睡眠分期、疾病分类、生成与纺锤波检测。",
    innovation: "用多预任务训练与时频深度融合处理可变通道配置，尝试建立睡眠解码的一体化模型。",
    limitation: "大规模回顾性基准不等于跨医院前瞻部署，设备差异和标签一致性仍需外部审计。",
    url: "https://www.nature.com/articles/s41467-025-67970-4",
  },
  {
    id: "noninvasive-word-decoding-2025",
    title: "从非侵入脑记录解码单词",
    titleEn: "Towards decoding individual words from non-invasive brain recordings",
    year: "2025", venue: "Nature Communications", type: "EEG 解码", signal: "EEG / MEG",
    summary: "在 723 名参与者、三种语言和约五百万词的数据上评估单词解码，比较跨设备、跨任务与跨人的扩展规律。",
    innovation: "用远大于以往的多数据集规模检验非侵入语言解码，并明确 MEG/EEG 与阅读/聆听之间的难度差异。",
    limitation: "EEG 单试次信噪比仍低，平均策略和实验范式对结果影响很大，距离自由交流尚远。",
    url: "https://www.nature.com/articles/s41467-025-65499-0",
  },
  {
    id: "du-in-2024",
    title: "Du-IN：面向中文词语解码的 sEEG 离散单元预训练",
    titleEn: "Du-IN: Discrete units-guided mask modeling for decoding speech from Intracranial Neural signals",
    year: "2024", venue: "NeurIPS", type: "sEEG 解码", signal: "sEEG",
    summary: "基于 12 名受试者的中文朗读 sEEG 数据，以脑区级 token 和离散码本掩码建模完成 61 词分类。",
    innovation: "针对 vSMC 与 STG 的异步活动设计脑区级表征，而非把所有电极粗略视为统一序列。",
    limitation: "词表和任务受控、样本规模有限；跨医院电极覆盖变化下的迁移仍未解决。",
    url: "https://proceedings.neurips.cc/paper_files/paper/2024/file/92559987ee79e42a2b01d534a54682ee-Paper-Conference.pdf",
  },
  {
    id: "neurosketch-2025",
    title: "NeuroSketch：跨 EEG、sEEG 与 ECoG 的解码架构审计",
    titleEn: "NeuroSketch: An Effective Framework for Neural Decoding via Systematic Architectural Optimization",
    year: "2025", venue: "arXiv 预印本", type: "解码方法", signal: "EEG / sEEG / ECoG",
    summary: "通过数千次受控实验比较卷积、循环、Transformer 及混合架构，在语音、视觉和听觉任务上提炼设计规律。",
    innovation: "系统拆解时空架构、潜空间与计算模块，强调充分优化常规模型的重要性。",
    limitation: "尚未同行评审；多数据集上的最佳结果仍需独立复现和统一数据泄漏审计。",
    url: "https://arxiv.org/abs/2512.09524",
  },
  {
    id: "seeg-speech-waveform-2024",
    title: "用深度学习从 sEEG 重建语音波形",
    titleEn: "Speech decoding from stereo-electroencephalography (sEEG) signals using advanced deep-learning methods",
    year: "2024", venue: "Journal of Neural Engineering", type: "sEEG 解码", signal: "sEEG",
    summary: "比较线性、循环与 Transformer 模型从 sEEG 重建语音波形，并分析少量关键电极的贡献。",
    innovation: "把解码对象从类别标签推进到连续声学波形，同时量化电极位置的重要性。",
    limitation: "受试者和电极覆盖受临床植入限制，跨人泛化与可懂度仍是主要瓶颈。",
    url: "https://pubmed.ncbi.nlm.nih.gov/38885688/",
  },
  {
    id: "speech-synthesis-framework-2024",
    title: "结合深度学习与可微语音合成的神经语音框架",
    titleEn: "A neural speech decoding framework leveraging deep learning and speech synthesis",
    year: "2024", venue: "Nature Machine Intelligence", type: "语音 BCI", signal: "ECoG",
    summary: "在 48 名参与者上以可解释声学参数连接 ECoG 解码器与可微语音合成器，支持因果实时处理。",
    innovation: "用语音自编码器提供低维声学监督，缓解配对神经—语音数据稀缺。",
    limitation: "数据来自癫痫术中或监测患者，尚未在失语目标人群中验证日常连续交流。",
    url: "https://www.nature.com/articles/s42256-024-00824-8",
  },
  {
    id: "highres-speech-2023",
    title: "高分辨率 µECoG 提升语音解码准确率",
    titleEn: "High-resolution neural recordings improve the accuracy of speech decoding",
    year: "2023", venue: "Nature Communications", type: "柔性电极", signal: "µECoG",
    summary: "比较高密度微型 ECoG 与较低空间分辨率记录，证明更丰富的时空神经信息能改善语音解码。",
    innovation: "把电极空间采样密度与非线性解码性能直接联系，为语音假体的阵列设计提供证据。",
    limitation: "以短时术中记录为主，高密度带来的长期封装、带宽和热量代价尚未解决。",
    url: "https://www.nature.com/articles/s41467-023-42555-1",
  },
];

export const technologies = [
  { id:"foundation-models", title:"神经基础模型", tag:"MODEL", maturity:"快速发展", summary:"从单任务小模型转向跨数据集、跨被试、跨通道配置的预训练表征。", points:["离散神经 tokenizer","掩码建模与对比学习","跨设备空间编码","严格的冻结编码器评估"] },
  { id:"flexible-electrodes", title:"柔性高密度电极", tag:"HARDWARE", maturity:"临床转化", summary:"降低机械失配和组织损伤，同时提升通道密度与皮层覆盖。", points:["µECoG 薄膜阵列","柔性皮层内线程","长期封装与生物相容性","可移除和可升级设计"] },
  { id:"wireless-implants", title:"全植入无线链路", tag:"SYSTEM", maturity:"临床验证", summary:"把供电、采集、压缩、传输和热管理整合为可长期使用的系统。", points:["近场供电","低功耗模拟前端","边缘压缩与事件检测","无线安全与延迟"] },
  { id:"speech-decoding", title:"流式语音解码", tag:"DECODING", maturity:"人体概念验证", summary:"从字符和词表分类迈向自然语音、音色和韵律的低延迟合成。", points:["声学中间表示","语言模型重排序","神经声码器","自适应在线解码"] },
  { id:"closed-loop", title:"闭环 BCI-FES", tag:"CLOSED LOOP", maturity:"临床探索", summary:"把运动意图解码与功能性电刺激连接，形成感觉—控制—反馈闭环。", points:["运动意图检测","FES 参数控制","感觉反馈","个体化康复策略"] },
  { id:"minimally-invasive", title:"微创神经接口", tag:"CLINICAL", maturity:"多路线竞争", summary:"硬膜外、硬膜下与血管内路线在信号质量、手术负担和可扩展性之间重新权衡。", points:["硬膜外 ECoG","硬膜下柔性阵列","血管内电极","微切口部署"] },
];

export const innovations = [
  { id:"generalization", title:"从“能解码”到“能泛化”", question:"模型换一个人、换一套电极后还能工作吗？", answer:"核心不再只是单数据集精度，而是共享神经表征、少样本适配和无监督在线校准。", metric:"跨被试 / 跨会话 / 跨设备" },
  { id:"bandwidth", title:"从通道数到有效信息带宽", question:"更多电极一定意味着更好的 BCI 吗？", answer:"真正关键的是每秒可靠信息量、系统延迟、长期稳定性和解码任务的匹配，而非孤立通道数。", metric:"ITR / latency / stability" },
  { id:"safety-resolution", title:"安全性与分辨率的新平衡", question:"如何在不伤脑的前提下获得高质量信号？", answer:"柔性材料、皮层表面高密度阵列、硬膜外与血管内路线正在形成多种临床折中。", metric:"侵入程度 / SNR / coverage" },
  { id:"daily-life", title:"从实验室成功到生活成功", question:"演示视频之后，用户能否每天稳定使用？", answer:"全植入、无线、低校准负担、家庭环境鲁棒性和可维护性，决定产品能否真正走出实验室。", metric:"home use / calibration burden" },
  { id:"human-machine-learning", title:"人与机器共同学习", question:"只训练算法够不够？", answer:"有效反馈会改变用户的神经策略；未来系统需要同时建模使用者学习与解码器适应。", metric:"co-adaptation / feedback" },
  { id:"reproducibility", title:"从排行榜到可复现证据", question:"精度提升能否跨数据集重现？", answer:"公开数据、统一基准、严格消融和模型审计，是把 BCI 研究从增量指标推向可积累知识的基础。", metric:"open data / benchmark / audit" },
];
